repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [ '--max-line-length=120', '--ignore=F403,F405,F841,W503' ]
        exclude: .*/migrations/.*

  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ['-l', '120', '-t', 'py311']
        exclude: .*/migrations/.*|.*urls\.py

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [ '--skip', 'B101,B110,B105' ]

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --ignore-init-module-imports
          - --in-place
          - --recursive

  - repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
      - id: isort
        args: ['--profile', 'black', '--filter-files', 'true']
        exclude: .*/migrations/.*

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --config mypy.ini mung_manager/
        always_run: true
        pass_filenames: false
        language: system
        types: [python]

default_language_version:
  python: python3.11
